#include "base64.h"
#include "utility.h"

#include <string.h>
#include <assert.h>
#include <stdio.h>

#ifdef __GNUC__
#define UNREACHABLE() __builtin_unreachable()
#else
#define UNREACHABLE() (void)0;
#endif

alignas(64) const char ALPHABET[64] = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
// generated by scripts/generate_reverse_alphabet.py
// note: 256 because the other characters of ascii don't exist
const unsigned char REVERSE_ALPHABET[256] = {
    ['A'] = 0,
    ['B'] = 1,
    ['C'] = 2,
    ['D'] = 3,
    ['E'] = 4,
    ['F'] = 5,
    ['G'] = 6,
    ['H'] = 7,
    ['I'] = 8,
    ['J'] = 9,
    ['K'] = 10,
    ['L'] = 11,
    ['M'] = 12,
    ['N'] = 13,
    ['O'] = 14,
    ['P'] = 15,
    ['Q'] = 16,
    ['R'] = 17,
    ['S'] = 18,
    ['T'] = 19,
    ['U'] = 20,
    ['V'] = 21,
    ['W'] = 22,
    ['X'] = 23,
    ['Y'] = 24,
    ['Z'] = 25,
    ['a'] = 26,
    ['b'] = 27,
    ['c'] = 28,
    ['d'] = 29,
    ['e'] = 30,
    ['f'] = 31,
    ['g'] = 32,
    ['h'] = 33,
    ['i'] = 34,
    ['j'] = 35,
    ['k'] = 36,
    ['l'] = 37,
    ['m'] = 38,
    ['n'] = 39,
    ['o'] = 40,
    ['p'] = 41,
    ['q'] = 42,
    ['r'] = 43,
    ['s'] = 44,
    ['t'] = 45,
    ['u'] = 46,
    ['v'] = 47,
    ['w'] = 48,
    ['x'] = 49,
    ['y'] = 50,
    ['z'] = 51,
    ['0'] = 52,
    ['1'] = 53,
    ['2'] = 54,
    ['3'] = 55,
    ['4'] = 56,
    ['5'] = 57,
    ['6'] = 58,
    ['7'] = 59,
    ['8'] = 60,
    ['9'] = 61,
    ['+'] = 62,
    ['/'] = 63,
};
const char PADDING = '=';

// encode full chunk
int encode_chunk_full(char out[static restrict 4], const char in_s[static restrict 3]) {
    const unsigned char* restrict in = (const unsigned char* restrict) in_s;
    unsigned long tmp = (unsigned long)(in[0]) << 16 | (unsigned long)(in[1]) << 8 | in[2];
    out[0] = ALPHABET[tmp >> 18 & 63];
    out[1] = ALPHABET[tmp >> 12 & 63];
    out[2] = ALPHABET[tmp >> 6 & 63];
    out[3] = ALPHABET[tmp & 63];
    return 4;
}

// encode partial chunk
// if i put a size for `in` gcc warns me
int encode_chunk_partial(char out[static restrict 4], const char in_s[restrict static 1], int length) {
    const unsigned char* restrict in = (const unsigned char* restrict) in_s;
    switch (length) {
        case 1: {
            unsigned long tmp = (unsigned long)in[0] << 16;
            out[0] = ALPHABET[tmp >> 18 & 63];
            out[1] = ALPHABET[tmp >> 12 & 63];
            out[2] = PADDING;
            out[3] = PADDING;
            return 2;
        }
        case 2: {
            unsigned long tmp = (unsigned long)in[0] << 16 | (unsigned long)in[1] << 8;
            out[0] = ALPHABET[tmp >> 18 & 63];
            out[1] = ALPHABET[tmp >> 12 & 63];
            out[2] = ALPHABET[tmp >> 6 & 63];
            out[3] = PADDING;
            return 3;
        }
        default:
            UNREACHABLE();
    }
}

int encode_chunk(char out[static restrict 4], const char in[restrict], int length) {
    switch (length) {
        case 1:
        case 2:
            return encode_chunk_partial(out, in, length);
        case 3:
            return encode_chunk_full(out, in);
        default:
            UNREACHABLE();
    }
}

int decode_chunk_full(char out[static restrict 3], const char in[static restrict 4]) {
    unsigned long tmp = REVERSE_ALPHABET[(int)in[0]] << 18
            | REVERSE_ALPHABET[(int)in[1]] << 12
            | REVERSE_ALPHABET[(int)in[2]] << 6
            | REVERSE_ALPHABET[(int)in[3]];
    out[0] = tmp >> 16 & 255;
    out[1] = tmp >> 8 & 255;
    out[2] = tmp & 255;
    return 3;
}

int decode_chunk_partial(char out[restrict], const char in[restrict], int length) {
    switch (length) {
        // This should never happen normally since 6 < 8 < 12 (i.e. even 8 ASCII
        // bits would require 2 base64 bytes. But let's handle the condition
        // anyways.
        case 1: {
            out[0] = REVERSE_ALPHABET[(int)in[0]] << 2;
            return 1;
        }
        case 2: {
            unsigned long tmp = REVERSE_ALPHABET[(int)in[0]] << 18
                    | REVERSE_ALPHABET[(int)in[1]] << 12;
            out[0] = tmp >> 16 & 255;
            return 1;
        }
        case 3: {
            unsigned long tmp = REVERSE_ALPHABET[(int)in[0]] << 18
                    | REVERSE_ALPHABET[(int)in[1]] << 12
                    | REVERSE_ALPHABET[(int)in[2]] << 6;
            out[0] = tmp >> 16 & 255;
            out[1] = tmp >> 8 & 255;
            return 2;
        }
        default:
            UNREACHABLE();
    }
}

int decode_chunk(char out[restrict], const char in[restrict], int length) {
    switch (length) {
        case 1:
        case 2:
        case 3:
            return decode_chunk_partial(out, in, length);
        case 4:
            return decode_chunk_full(out, in);
        default: 
            UNREACHABLE();
    }
}

// decode but auto-detect padding
int decode_chunk_padding(char out[static restrict 3], const char in[static restrict 4]) {
    int length;
    const char* padding_ptr = (const char*)memchr((const int*)in, '=', 4);
    if (!padding_ptr) {
        return decode_chunk_full(out, in);
    } else {
        length = padding_ptr - in;
        return decode_chunk_partial(out, in, length);
    }
}