#include "base64.h"

#include <string.h>
#include <assert.h>

static const char ALPHABET[] = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
// generated by scripts/generate_reverse_alphabet.py
// note: 256 because the other characters of ascii don't exist
static const unsigned char REVERSE_ALPHABET[256] = {
    ['A'] = 0,
    ['B'] = 1,
    ['C'] = 2,
    ['D'] = 3,
    ['E'] = 4,
    ['F'] = 5,
    ['G'] = 6,
    ['H'] = 7,
    ['I'] = 8,
    ['J'] = 9,
    ['K'] = 10,
    ['L'] = 11,
    ['M'] = 12,
    ['N'] = 13,
    ['O'] = 14,
    ['P'] = 15,
    ['Q'] = 16,
    ['R'] = 17,
    ['S'] = 18,
    ['T'] = 19,
    ['U'] = 20,
    ['V'] = 21,
    ['W'] = 22,
    ['X'] = 23,
    ['Y'] = 24,
    ['Z'] = 25,
    ['a'] = 26,
    ['b'] = 27,
    ['c'] = 28,
    ['d'] = 29,
    ['e'] = 30,
    ['f'] = 31,
    ['g'] = 32,
    ['h'] = 33,
    ['i'] = 34,
    ['j'] = 35,
    ['k'] = 36,
    ['l'] = 37,
    ['m'] = 38,
    ['n'] = 39,
    ['o'] = 40,
    ['p'] = 41,
    ['q'] = 42,
    ['r'] = 43,
    ['s'] = 44,
    ['t'] = 45,
    ['u'] = 46,
    ['v'] = 47,
    ['w'] = 48,
    ['x'] = 49,
    ['y'] = 50,
    ['z'] = 51,
    ['0'] = 52,
    ['1'] = 53,
    ['2'] = 54,
    ['3'] = 55,
    ['4'] = 56,
    ['5'] = 57,
    ['6'] = 58,
    ['7'] = 59,
    ['8'] = 60,
    ['9'] = 61,
    ['+'] = 62,
    ['/'] = 63,
};
static const char PADDING = '=';

// encode full block
void encode_block_full(char out[static 4], const char in[static 3]) {
    int tmp = (int)in[0] << 16 | (int)in[1] << 8 | (int)in[2];
    out[0] = ALPHABET[tmp >> 18 & 63];
    out[1] = ALPHABET[tmp >> 12 & 63];
    out[2] = ALPHABET[tmp >> 6 & 63];
    out[3] = ALPHABET[tmp & 63];
}

// encode partial block
// if i put a size for `in` gcc warns me
void encode_block_partial(char out[static 4], const char in[], int length) {
    switch (length) {
        case 1: {
            int tmp = (int)in[0] << 16;
            out[0] = ALPHABET[tmp >> 18 & 63];
            out[1] = ALPHABET[tmp >> 12 & 63];
            out[2] = PADDING;
            out[3] = PADDING;
            return;
        }
        case 2: {
            int tmp = (int)in[0] << 16 | (int)in[1] << 8;
            out[0] = ALPHABET[tmp >> 18 & 63];
            out[1] = ALPHABET[tmp >> 12 & 63];
            out[2] = ALPHABET[tmp >> 6 & 63];
            out[3] = PADDING;
            return;
        }
        default:
            assert(0);
    }
}

void encode_block(char out[static 4], const char in[], int length) {
    switch (length) {
        case 1:
        case 2:
            encode_block_partial(out, in, length);
            return;
        case 3:
            encode_block_full(out, in);
            return;
    }
}

void decode_block_full(char out[static 3], const char in[static 4]) {
    int tmp = REVERSE_ALPHABET[(int)in[0]] << 18
            | REVERSE_ALPHABET[(int)in[1]] << 12
            | REVERSE_ALPHABET[(int)in[2]] << 6
            | REVERSE_ALPHABET[(int)in[3]];
    out[0] = tmp >> 16 & 255;
    out[1] = tmp >> 8 & 255;
    out[2] = tmp & 255;
}

void decode_block_partial(char out[], const char in[], int length) {
    switch (length) {
        // This should never happen normally since 6 < 8 < 12 (i.e. even 8 ASCII
        // bits would require 2 base64 bytes. But let's handle the condition
        // anyways.
        case 1: {
            out[0] = REVERSE_ALPHABET[(int)in[0]] << 2;
            return;
        }
        case 2: {
            int tmp = REVERSE_ALPHABET[(int)in[0]] << 18
                    | REVERSE_ALPHABET[(int)in[1]] << 12;
            out[0] = tmp >> 16 & 255;
            return;
        }
        case 3: {
            int tmp = REVERSE_ALPHABET[(int)in[0]] << 18
                    | REVERSE_ALPHABET[(int)in[1]] << 12
                    | REVERSE_ALPHABET[(int)in[2]] << 6;
            out[0] = tmp >> 16 & 255;
            out[1] = tmp >> 8 & 255;
            return;
        }
        default:
            assert(0);
    }
}

void decode_block(char out[], const char in[], int length) {
    switch (length) {
        case 1:
        case 2:
        case 3:
            decode_block_partial(out, in, length);
            return;
        case 4:
            decode_block_full(out, in);
            return;
    }
}

// decode but auto-detect padding
void decode_block_padding(char out[static 3], const char in[static 4]) {
    int length;
    const char* padding_ptr = (const char*)memchr((const void*)in, '=', 4);
    if (!padding_ptr) {
        return decode_block_full(out, in);
    } else {
        length = padding_ptr - in;
        decode_block_partial(out, in, length);
    }
}