#include "base64.h"
#include "utility.h"

#include <string.h>
#include <assert.h>
#include <stdio.h>
#include <stdint.h>

alignas(64) const char ALPHABET[64] = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
// generated by scripts/generate_reverse_alphabet.py
// note: 256 because the other characters of ascii don't exist
const unsigned char REVERSE_ALPHABET[256] = "\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff>\xff\xff\xff?456789:;<=\xff\xff\xff\xff\xff\xff\xff\x00\x01\x02\x03\x04\x05\x06\x07\x08\t\n\x0b\x0c\r\x0e\x0f\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\xff\xff\xff\xff\xff\xff\x1a\x1b\x1c\x1d\x1e\x1f !\"#$%&'()*+,-./0123\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff";
const char PADDING = '=';

// encode full chunk
hot int encode_chunk_full(char out[static restrict 4], const char in_s[static restrict 3]) {
    const unsigned char* restrict in = (const unsigned char* restrict) in_s;
    unsigned long tmp = (unsigned long)(in[0]) << 16 | (unsigned long)(in[1]) << 8 | in[2];
#if X86_64
    uint32_t res = ALPHABET[tmp >> 18 & 63] |
                        ALPHABET[tmp >> 12 & 63] << 8 |
                        ALPHABET[tmp >> 6 & 63] << 16 |
                        ALPHABET[tmp & 63] << 24;
    *(uint32_t*)out = res;
#else
    out[0] = ALPHABET[tmp >> 18 & 63];
    out[1] = ALPHABET[tmp >> 12 & 63];
    out[2] = ALPHABET[tmp >> 6 & 63];
    out[3] = ALPHABET[tmp & 63];
#endif
    return 4;
}

// encode partial chunk
// if i put a size for `in` gcc warns me
int encode_chunk_partial(char out[static restrict 4], const char in_s[restrict], int length) {
    const unsigned char* restrict in = (const unsigned char* restrict) in_s;
    switch (length) {
        case 1: {
            unsigned long tmp = (unsigned long)in[0] << 16;
            out[0] = ALPHABET[tmp >> 18 & 63];
            out[1] = ALPHABET[tmp >> 12 & 63];
            out[2] = PADDING;
            out[3] = PADDING;
            return 2;
        }
        case 2: {
            unsigned long tmp = (unsigned long)in[0] << 16 | (unsigned long)in[1] << 8;
            out[0] = ALPHABET[tmp >> 18 & 63];
            out[1] = ALPHABET[tmp >> 12 & 63];
            out[2] = ALPHABET[tmp >> 6 & 63];
            out[3] = PADDING;
            return 3;
        }
        default:
            unreachable();
    }
}

int encode_chunk(char out[static restrict 4], const char in[restrict], int length) {
    switch (length) {
        case 1:
        case 2:
            return encode_chunk_partial(out, in, length);
        case 3:
            return encode_chunk_full(out, in);
        default:
            unreachable();
    }
}

int decode_chunk_full(char out[static restrict 3], const char in[static restrict 4]) {
    unsigned long tmp = REVERSE_ALPHABET[(int)in[0]] << 18
            | REVERSE_ALPHABET[(int)in[1]] << 12
            | REVERSE_ALPHABET[(int)in[2]] << 6
            | REVERSE_ALPHABET[(int)in[3]];
    out[0] = tmp >> 16 & 255;
    out[1] = tmp >> 8 & 255;
    out[2] = tmp & 255;
    return 3;
}

int decode_chunk_partial(char out[restrict], const char in[restrict], int length) {
    switch (length) {
        // This should never happen normally since 6 < 8 < 12 (i.e. even 8 ASCII
        // bits would require 2 base64 bytes. But let's handle the condition
        // anyways.
        case 1: {
            out[0] = REVERSE_ALPHABET[(int)in[0]] << 2;
            return 1;
        }
        case 2: {
            unsigned long tmp = REVERSE_ALPHABET[(int)in[0]] << 18
                    | REVERSE_ALPHABET[(int)in[1]] << 12;
            out[0] = tmp >> 16 & 255;
            return 1;
        }
        case 3: {
            unsigned long tmp = REVERSE_ALPHABET[(int)in[0]] << 18
                    | REVERSE_ALPHABET[(int)in[1]] << 12
                    | REVERSE_ALPHABET[(int)in[2]] << 6;
            out[0] = tmp >> 16 & 255;
            out[1] = tmp >> 8 & 255;
            return 2;
        }
        default:
            unreachable();
    }
}

int decode_chunk(char out[restrict], const char in[restrict], int length) {
    switch (length) {
        case 1:
        case 2:
        case 3:
            return decode_chunk_partial(out, in, length);
        case 4:
            return decode_chunk_full(out, in);
        default: 
            unreachable();
    }
}

// decode but auto-detect padding
int decode_chunk_padding(char out[static restrict 3], const char in[static restrict 4]) {
    int length;
    const char* padding_ptr = (const char*)memchr((const int*)in, '=', 4);
    if (!padding_ptr) {
        return decode_chunk_full(out, in);
    } else {
        length = padding_ptr - in;
        return decode_chunk_partial(out, in, length);
    }
}